#!/bin/bash
qemu-system-x86_64 \
	-enable-kvm \
	-machine q35,accel=kvm \
	-m 3000 -smp 2 -cpu host \
	-accel kvm \
	-vga virtio \
	-display gtk,gl=on \
	-hda wowx86.qcow2\
	-soundhw ac97 \
	-serial mon:stdio \
	-boot menu=on \
	-netdev user,id=tumo,net=192.168.77.0/24,dhcpstart=192.168.77.7,hostfwd=tcp:127.0.0.1:5555-:22 \
	-device virtio-net-pci,netdev=tumo \
	-usb -device usb-kbd\
	
